import type { Metadata } from "next";
import { EngineShell, EngineHero, StepStrip, FeatureGrid, DemoStrip } from "@/components/EnginePage";

export const metadata: Metadata = {
  title: "Social Media Marketing — Jhalak",
  description: "Instagram-ready reels generated from your catalogue. Pick an item, get reels, post.",
};

export default function SocialMediaPage() {
  return (
    <EngineShell>
      <EngineHero
        kicker="Engine 3 · Social Media Marketing"
        title="Reels for your business — without shooting a single video."
        lede="Reels are how customers discover local businesses now. Pick any item from your catalogue and get Instagram-ready vertical reels, generated for you."
        ctaLabel="Get started"
      />
      <StepStrip
        steps={[
          { n: "1", t: "Pick an item", d: "Any photo from your catalogue — a bestseller, a new arrival, your space." },
          { n: "2", t: "Get a reel pack", d: "Two 9:16 reel variants per item — a clean showcase and a promo mood — generated by AI video models." },
          { n: "3", t: "Download & post", d: "Preview in your dashboard, download, and post to Instagram and WhatsApp Status. You stay in control of your accounts." },
        ]}
      />
      <FeatureGrid
        items={[
          { icon: "📱", t: "Made for Instagram", d: "Vertical 9:16, short and scroll-stopping — the format the algorithm actually rewards." },
          { icon: "🎛️", t: "Sensible limits", d: "Reel generation is capped per business so costs stay predictable — no surprise bills, ever." },
          { icon: "🔜", t: "Provider-gated preview", d: "The reel studio is built and ready; AI video switches on in this preview as soon as the video provider key is connected." },
        ]}
      />
      <DemoStrip />
    </EngineShell>
  );
}
